sudo: required
services:
  - docker

before_install:
  -docker build -t maeri/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true maeri/react-test npm test

after_success:
  - docker build -t maeri/docker-k8s-complex-client ./client
  - docker build -t maeri/docker-k8s-complex-nginx ./nginx
  - docker build -t maeri/docker-k8s-complex-server ./server
  - docker build -t maeri/docker-k8s-complex-worker ./worker
  
  # login to docker CLI in single command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push them to docker hub
  - docker push maeri/docker-k8s-complex-client
  - docker push maeri/docker-k8s-complex-nginx
  - docker push maeri/docker-k8s-complex-server
  - docker push maeri/docker-k8s-complex-worker