sudo: required
services:
  - docker

before_install:
  - docker build -t maeri/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true maeri/react-test npm test

after_success:
  - docker build -t maeri/docker-k8s-complex-client ./client
  - docker build -t maeri/docker-k8s-complex-nginx ./nginx
  - docker build -t maeri/docker-k8s-complex-server ./server
  - docker build -t maeri/docker-k8s-complex-worker ./worker
  
  # login to docker CLI in single command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take those images and push them to docker hub
  - docker push maeri/docker-k8s-complex-client
  - docker push maeri/docker-k8s-complex-nginx
  - docker push maeri/docker-k8s-complex-server
  - docker push maeri/docker-k8s-complex-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: docker-k8s-complex
  env: DockerK8sComplex-env
  bucket_name: elasticbeanstalk-eu-west-2-471512436894
  bucket_path: docker-k8s-complex
  on: 
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"