apiVersion: skaffold/v1beta12
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: maeri/docker-k8s-complex-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: '**/*.js'
            dest: .
          - src: '**/*.css'
            dest: .
          - src: '**/*.html'
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml