apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:9.6.5
          command: ['sh', '-c', 'until pg_isready -h postgres-cluster-ip-service -p 5432; do echo waiting for database; sleep 2; done;']
      containers:
        - name: server
          image: maeri/docker-k8s-complex-server:latest
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: REDIS_HOST
              value : redis-cluster-ip-service
            - name: REDIS_PORT
              value : '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGDATABASE
              value : postgres              
            - name: PGPORT
              value: '5432'
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD